title: My Story
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://amazonKamath.github.io/mystorybook

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/amazonKamath/mystorybook
